// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: My_SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_AdPanel = NULL;
lv_obj_t * ui_InfoPanel = NULL;
lv_obj_t * ui_LabelFloor = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_LabelAlert = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AdPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_AdPanel, 750);
    lv_obj_set_height(ui_AdPanel, 600);
    lv_obj_set_align(ui_AdPanel, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_AdPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AdPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AdPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_InfoPanel, 275);
    lv_obj_set_height(ui_InfoPanel, 600);
    lv_obj_set_x(ui_InfoPanel, 376);
    lv_obj_set_y(ui_InfoPanel, 0);
    lv_obj_set_align(ui_InfoPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_InfoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFloor = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelFloor, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_LabelFloor, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_LabelFloor, 377);
    lv_obj_set_y(ui_LabelFloor, -39);
    lv_obj_set_align(ui_LabelFloor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFloor, "-- F");
    lv_obj_set_style_text_color(ui_LabelFloor, lv_color_hex(0xA43C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFloor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFloor, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFloor, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 373);
    lv_obj_set_y(ui_LabelTemp, 57);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "Temp: --.- C Humi: -- %");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x2FA4B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAlert = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelAlert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAlert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAlert, 375);
    lv_obj_set_y(ui_LabelAlert, 167);
    lv_obj_set_align(ui_LabelAlert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAlert, " WARNING: SYSTEM ALERT ");
    lv_obj_add_flag(ui_LabelAlert, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelAlert, lv_color_hex(0xEF0931), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAlert, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAlert, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_AdPanel = NULL;
    ui_InfoPanel = NULL;
    ui_LabelFloor = NULL;
    ui_LabelTemp = NULL;
    ui_LabelAlert = NULL;

}
